version: '3.8'

services:
  activity-config:
    build: 
      context: .
      args:
        - NODE_ENV=development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DEPLOY_ENV=test
    env_file:
      - .env.test
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      # 开发模式下挂载源代码以支持热重载
      - .:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge