version: '3.8'

services:
  activity-config:
    build: 
      context: .
      args:
        - NODE_ENV=production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DEPLOY_ENV=prod
    env_file:
      - .env.prod
    extra_hosts:
      - "proactivity.meequ.cn:172.18.26.11"
      - "testmqgitapp.meequ.cn:172.18.26.11"
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge