version: '3.8'

services:
  activity-config:
    build: 
      context: .
      args:
        - NODE_ENV=production  # 即使是测试环境也用生产构建避免之前的错误
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production    # 使用生产构建
      - DEPLOY_ENV=test        # 但连接测试后端
    env_file:
      - .env.test
    extra_hosts:
      - "proactivity.meequ.cn:172.18.26.11"
      - "testmqgitapp.meequ.cn:172.18.26.11"
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge