services:
  activity-config-prod:
    build: 
      context: .
      args:
        - NODE_ENV=production
    ports:
      - "3020:3000"  # 正式环境使用3020端口
    environment:
      - NODE_ENV=production
      - DEPLOY_ENV=prod
      - PORT=3000              # 容器内部端口保持3000
    env_file:
      - .env.prod
    extra_hosts:
      - "proactivity.meequ.cn:172.18.26.11"
      - "testmqgitapp.meequ.cn:172.18.26.11"
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network-prod
    container_name: activity-config-prod

networks:
  app-network-prod:
    driver: bridge