import type { Metadata } from 'next';
import './globals.css';
import { AuthProvider } from '../components/auth/AuthProvider';
import AuthGuard from '../components/auth/AuthGuard';

export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
    title: 'Sheng Ba Activity Setting Page',
    description: 'Generated by Onlook',
    openGraph: {
        title: 'Sheng Ba Activity Setting Page',
        description: 'Generated by Onlook',
        url: 'a2gut9fgrk4ro0ktapnby.onlook.live',
        siteName: 'Sheng Ba Activity Setting Page',
        type: 'website',
        images: [
            {
                url: '/images/01f24d30c5bfd395513c7e284190f3bd.png',
                width: 1200,
                height: 630,
                alt: 'Sheng Ba Activity Setting Page',
            },
        ],
    },
    metadataBase: new URL('https://a2gut9fgrk4ro0ktapnby.onlook.live/'),
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="zh-CN" data-oid="xdzh8s8">
            <body className="" data-oid="t2ln..8">
                <AuthProvider>
                    <AuthGuard>
                        {children}
                    </AuthGuard>
                </AuthProvider>
            </body>
        </html>
    );
}
